module.exports = {
  CREATED_STATUS_CODE: 201,
  SUCCESS_RESPPONSE_STATUS_CODE: 200,
  BAD_REQUEST_STATUS_CODE: 400,
  NOT_FOUND_STATUS_CODE: 404,
  TOO_MANY_REQUEST_STATUS_CODE: 429,
  INTERNAL_SERVER_STATUS_CODE: 500,
  BAD_REQUEST_STATUS_MESSAGE: 'Bad request',
  INTERNAL_SERVER_MESSAGE: 'Internal server error!',
  NOT_FOUND_STATUS_MESSAGE: 'Not found!'
};
